baseURL = 'https://school.gurfoto.ru/'
languageCode = 'ru'
title = 'Фотошкола в Ростове. Индивидуальное обучение'

theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ru"
# Enable comments by entering your Disqus shortname
  disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
# paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false



# [permalinks]
#    blog = "/blog/:year/:month/:day/:filename/"


[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true