
# Main menu
[[main]]
    name       = "Обучение"
    identifier = "menu.home"
    url        = "/training/"
    weight     = 1

[[main]]
    name       = "Мастера фотографии"
    identifier = "menu.invisibility"
    url        = "/invisibility/"
    weight     = 2


[[main]]
    name       = "Об авторе"
    identifier = "menu.aboutauthor"
    url        = "/aboutauthor/"
    weight     = 3

[[main]]
    name       = "Контакты"
    identifier = "contact"
    url        = "/contact/"
    weight     = 4


# Top bar social links menu


# [[topbar]]
#    weight = 2
#    name = "Email"
#    url = "mailto:gurfoto@gmail.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"
