
# Main menu
[[main]]
    name       = "Обучение"
    identifier = "menu.home"
    url        = "/training/"
    weight     = 1

[[main]]
    name       = "Как устроен курс"
    url        = "/training/"
    weight     = 1
    parent     = "menu.home"

[[main]]
    name       = "Принципы фотографии и техника съемки"
    url        = "/technic/"
    weight     = 2
    parent     = "menu.home"

[[main]]
    name       = "Построение кадра и начала композиции"
    url        = "/composition/"
    weight     = 3
    parent     = "menu.home"

[[main]]
    name       = "Основы цветокоррекции и ретуши"
    url        = "/imgeditor/"
    weight     = 4
    parent     = "menu.home"

[[main]]
    name       = "Визуальное восприятие изображений"
    url        = "/gestalt/"
    weight     = 5
    parent     = "menu.home"

[[main]]
    name       = "Фотосъемка в естественном свете: пленэр"
    url        = "/plenair/"
    weight     = 6
    parent     = "menu.home"
    
[[main]]
    name       = "Студийная съемка: работа с импульсным светом"
    url        = "/photostudio/"
    weight     = 7
    parent     = "menu.home"

[[main]]
    name       = "Предметная съемка. Макросъемка"
    url        = "/objectphoto/"
    weight     = 8
    parent     = "menu.home"

[[main]]
    name       = "Интерьерная съемка"
    url        = "/interiorphoto/"
    weight     = 9
    parent     = "menu.home"

[[main]]
    name       = "Панорамная съемка. Создание сферических панорам"
    url        = "/pano/"
    weight     = 10
    parent     = "menu.home"

[[main]]
    name       = "Мастера фотографии"
    identifier = "menu.invisibility"
    url        = "/invisibility/"
    weight     = 2


[[main]]
    name       = "Об авторе"
    identifier = "menu.aboutauthor"
    url        = "/aboutauthor/"
    weight     = 3

[[main]]
    name       = "Контакты"
    identifier = "contact"
    url        = "/contact/"
    weight     = 4


# Top bar social links menu


# [[topbar]]
#    weight = 2
#    name = "Email"
#    url = "mailto:gurfoto@gmail.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"
