
#    viewMorePostLink = ""
#    author = "DevCows"
#    defaultKeywords = ["devcows", "hugo", "go"]
#    mainSections = ["blog"]
#    defaultDescription = "Site template made by Devcows using Hugo"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    #  formspree_action = "https://formspree.io/sample/of/endpoint"
    #  contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
        enableRecaptchaInContactForm = false
        googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Фотошкола в Ростове ─ проект фотографического агентства GurFoto.Ru.</p>"
    copyright = "Copyright GurFoto.Ru (c) 2013 - 2024."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "GurFoto.Ru"

    logo = "img/logo3.png"
    logo_small = "img/logo-small3.png"
    contact_url = "/contact"
    address = """<p><strong>GurFoto.Ru</strong>
        <br>Россия
        <br>Ростов-на-Дону
        <br><b>+7 919 874 20 24</b> (тел./WhatsApp)
      </p>
      """

      # Enable or disable top bar with social icons
[topbar]
    enable = true
    text = """<p><a href="tel:+79198742024" data-animate-hover="pulse">+7 919 874 20 24 <i class="fas fa-phone"></i></a>"""
#    text = """<p class="hidden-sm hidden-xs">+7 919 874 20 24</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+7 919 874 20 24" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:gurfoto@gmail.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[widgets]
    categories = true
    tags = true
    search = true

[carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Школа фотографии в Ростове"
    subtitle = "Для получения полной информации звоните **+7 919 874 20 24**"
    link_url = "/training"
    link_text = "Подробней"

[clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[recent_posts]
    enable = true
    title = "Эффективность курса"
    subtitle = "Учебный план формируется для каждого студента индивидуально, с учетом уровня его подготовки. Акцент обучения делается на практических заданиях. Бесплатная консультационная поддержка не ограничена временем и продолжается пока в ней есть необходимость."
    hide_summary = false

[school_name]
    title = "Школа фотографии в Ростове"
    subtitle = ""

[footer.recent_posts]
    enable = false